import Footer from './components/Layout/Footer'
import Navbar from './components/Layout/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Remote Web Dynamics | Welcome',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
